services:
  - type: web
    name: shl-recommender
    runtime: docker
    plan: free
    region: oregon
    branch: main
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: GROQ_MODEL
        value: llama-3.1-8b-instant
      - key: HF_HUB_DISABLE_SYMLINKS_WARNING
        value: "1"
      - key: GROQ_API_KEY
        sync: false
